-- 2022년 3월 오프라인/온라인 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량 조회
-- OFFLINE_SALE 테이블 USER_ID는 NULL로 표시
-- 판매일 오름차순 / 상품ID 오름차순 / 유저ID 오름차순
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID AS PRODUCT_ID,
       USER_ID AS USER_ID,
       SALES_AMOUNT AS SALES_AMOUNT
FROM (SELECT SALES_DATE,
       PRODUCT_ID AS PRODUCT_ID,
       USER_ID AS USER_ID,
       SALES_AMOUNT AS SALES_AMOUNT
FROM ONLINE_SALE
UNION ALL
SELECT SALES_DATE,
       PRODUCT_ID AS PRODUCT_ID,
       NULL AS USER_ID,
       SALES_AMOUNT AS SALES_AMOUNT
FROM OFFLINE_SALE) AS C
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
;