-- 세단 or SUV 인 자동차 중 2022-11-01 ~ 2022-11-30 대여 가능하고 30일간 대여 금액 50 ~ 200 미만인 차에 대해 자동차 ID, 종류, 대여 금액(FEE) 리스트 출력
-- 대여 금액 내림차순, 종류 오름차순, ID 내림차순

SELECT A.CAR_ID,
       A.CAR_TYPE,
       ROUND(A.DAILY_FEE * 30 * (1-C.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR  A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
        AND B.START_DATE <= '2022-11-30'
        AND B.END_DATE >= '2022-11-01'
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
        AND C.DURATION_TYPE = '30일 이상'
WHERE B.CAR_ID IS NULL
AND A.CAR_TYPE IN ('SUV', '세단')
HAVING 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC