-- 년, 월, 성별 별 상품 구매 회원 수 집계
-- 년, 월, 성별 기준 오름차순 / 성별 없으면 제외

SELECT YEAR(O.SALES_DATE) AS YEAR,
       MONTH(O.SALES_DATE) AS MONTH,
       U.GENDER,
       COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM USER_INFO AS U
    JOIN (SELECT USER_ID, SALES_DATE
          FROM ONLINE_SALE
          GROUP BY USER_ID, SALES_DATE) AS O
    ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3