-- 노선별 노선, 총 누계 거리, 평균 역 사이 거리 조회
-- 누계거리 = TOTAL_DISTANCE, 평균 역 사이 거리 = AVERAGE_DISTANCE
-- 둘째자리, 셋째자리 반올림 -> 단위 KM 까지 출력
-- 누계거리 내림차순

SELECT ROUTE, 
       CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, 
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC