# 2021년에 가입한 회원
WITH TOTAL_USER AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),

# 2021년에 가입했으면서 상품을 구매한 회원
BUYING_USER AS (
    SELECT DISTINCT O.USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE AS O
        JOIN TOTAL_USER AS U
        ON O.USER_ID = U.USER_ID
)

SELECT YEAR, 
       MONTH, 
       COUNT(*) AS PURCHASED_USERS,
       ROUND(COUNT(*) / (SELECT COUNT(*) FROM TOTAL_USER), 1) AS PURCHASED_RATIO
FROM BUYING_USER
GROUP BY YEAR, MONTH
ORDER BY 1, 2

# SELECT YEAR(B.SALES_DATE) AS YEAR, 
#        MONTH(B.SALES_DATE) AS MONTH, 
#        COUNT(B.USER_ID) AS PURCHASED_USERS,
#        ROUND(COUNT(A.USER_ID) / COUNT(B.USER_ID), 1)
#        # ROUND(COUNT(A.USER_ID) / COUNT(B.USER_ID), 1)
# FROM TOTAL_USER AS A
#     LEFT OUTER JOIN BUYING_USER AS B
#     ON A.USER_ID = B.USER_ID
# GROUP BY YEAR, MONTH
# HAVING YEAR IS NOT NULL