WITH RECURSIVE G_ECOLI AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ED.ID, ED.PARENT_ID, G_ECOLI.GENERATION + 1
    FROM G_ECOLI
        JOIN ECOLI_DATA ED
        ON ED.PARENT_ID = G_ECOLI.ID
)

SELECT COUNT(*) COUNT, GENERATION
FROM G_ECOLI
WHERE ID NOT IN (SELECT PARENT_ID 
                 FROM ECOLI_DATA
                 WHERE PARENT_ID IS NOT NULL
                 GROUP BY PARENT_ID 
                )
GROUP BY GENERATION
;