-- 트럭 대여기록 -> 대여기록별 대여 금액 구하여 대여 기록 ID와 금액 리스트 출력
-- 금액 내림차순, ID 내림차순
WITH RENTAL_DURATION AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAYS,
           CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
                END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT HISTORY_ID,
       CASE WHEN H.DURATION_TYPE IS NULL THEN ROUND(DAILY_FEE * H.RENTAL_DAYS, 0)
            ELSE ROUND(DAILY_FEE * H.RENTAL_DAYS * (1 - DISCOUNT_RATE / 100), 0)
            END AS FEE
FROM RENTAL_DURATION AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON C.CAR_ID = H.CAR_ID
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
        ON H.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC