SELECT B.FLAVOR
FROM (
    SELECT A.FLAVOR, SUM(A.TOTAL_ORDER) AS T
    FROM (
        SELECT F.FLAVOR, F.TOTAL_ORDER
        FROM FIRST_HALF AS F
        UNION ALL
        SELECT J.FLAVOR, J.TOTAL_ORDER
        FROM JULY AS J
    ) AS A
    GROUP BY A.FLAVOR
    ORDER BY T DESC
) AS B
LIMIT 3