SELECT DISTINCT D.ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
    JOIN (
        SELECT *
        FROM SKILLCODES
        WHERE CATEGORY = 'Front End'
    ) AS S
    ON D.SKILL_CODE & S.CODE = S.CODE
ORDER BY 1