SELECT MP.MEMBER_NAME,
       RR.REVIEW_TEXT, 
       DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW AS RR
    JOIN MEMBER_PROFILE AS MP
    ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(MEMBER_ID)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) DESC
        LIMIT 1
    )
)
ORDER BY 3, 2