-- 부모의 형질을 모두 보유한 대장균 출력
-- ID, GENOTYPE, PARENT_GENOTYPE / ID 오름차순

SELECT C.ID, C.GENOTYPE GENOTYPE, P.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA C
    JOIN (SELECT ID, GENOTYPE
          FROM ECOLI_DATA
         ) P
    ON C.PARENT_ID = P.ID
WHERE PARENT_ID IS NOT NULL AND C.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY C.ID
;