-- SKILLCODES 이름, 스킬범주, 스킬코드(2 제곱수)
-- DEVELOPERS ID, 이름, 성, 이메일, 스킬코드

-- DEVELOPERS 에서 파이썬 OR C# 스킬을 가진 개발자 정보 출력
-- ID, 이메일, 이름, 성 / ID 오름차순

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID;