-- 1. 연도별 가장 큰 대장균의 크기를 구한다.
-- 2. 각 연도별 크기를 가장 큰 대장균과 뺀다.
-- 3. 이를 출력한다.

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, ABS(A.SIZE_OF_COLONY - B.MAX_SIZE) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
    JOIN
    (
        SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR
    ) AS B
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV