-- 세단 10월 대여 시작 기록 자동차 ID 리스트
-- 중복 X / ID 내림차순
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단' AND H.START_DATE LIKE '2022-10%'
ORDER BY 1 DESC