-- 2022-01 의 카테고리 별 도서 판매량을 합산해서 출력 / 카테고리명 오름차순

SELECT B.CATEGORY, SUM(BS.TS) AS TOTAL_SALES
FROM BOOK AS B
    JOIN (
        SELECT BOOK_ID, SUM(SALES) AS TS
        FROM BOOK_SALES
        WHERE SALES_DATE LIKE '2022-01%'
        GROUP BY BOOK_ID
    ) AS BS
    ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY